apiVersion: v1
kind: ServiceAccount
metadata:
  name: mortgage-review-agent-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::666127452756:role/mortgage-review-agent-role